mbuild/formats/hoomdxml.py, mbuild/formats/lammpsdata.py
Cleaned up some code in the LAMMPS and HOOMD writers to make more readable.  The LAMMPS writer should now support arbitrary atom names (previously names were required to be in a "forcefield_#" format).
=> Minor adjustments to LAMMPS and HOOMD writers

mbuild/recipes/polymer.py
Ran into an issue in a script where the Polymer class was being erroneously instantiated, and the bug took a while to find because no error was being generated.  This isn't a big issue either way, but I think it makes more sense to require the user to provide a length for their polymer.
=> Converted 'n' in polymer class to a required argument

mbuild/formats/hoomdxml.py, mbuild/tests/test_hoomdxml.py
Fixed a minor bug where rigid bodies are written to the hoomdxml file.  Also added a unit test for saving a compound containing rigid bodies.
=> Minor fix to hoomdxml writer

mbuild/examples/pmpc/initiator.py, mbuild/examples/pmpc/mpc.py, mbuild/examples/tnp/sphere.py, mbuild/lib/atoms/c3.py, mbuild/lib/atoms/h.py, mbuild/lib/moieties/ester.py, mbuild/lib/surfaces/amorphous_silica.py, mbuild/lib/surfaces/betacristobalite.py, mbuild/pattern.py, mbuild/port.py, mbuild/recipes/silica_interface.py, mbuild/tests/test_port.py
Rather than ports being located at the origin upon creation, they are now shifted to the location of the anchor particle if one is provided.  This approach seems a bit more intuitive.  This also means that previous scripts where port locations are shifted manually will now be broken.  I've removed the manual shifting of ports created with recipes, library compounds, and the examples.  I've also changed port rotations from "rotate_about_..." to "spin_..." since ports are no longer always located at the origin.
=> Automatically shifting port location to anchor location

mbuild/lib/moieties/peg.py
- The "up" port of PEG mlcl = 1.43 - 0.7 = 0.73 AA
=> Fix "up" port of PEG mlcl

mbuild/compound.py, mbuild/tests/test_compound.py
Raise an error if the file exists and overwrite == False.
This is checked before figuring out which writer needs to be used, so
that the internal writers won't ever see the overwrite kwarg.
Resolves #252
=> Check if file exists in compound.save

.gitignore, .travis.yml
Now both osx and linux tests will test the same versions of python which is important for the conda builds.
I've also added .env/ to the .gitignore file to support virtualenv
=> parity now between osx and linux tests

mbuild/coordinate_transform.py
This file had windows line endings so it shows that everything has been changed. Other than some simple pep8 fixes I did two things of significance:
1. I got rid of `from numpy import *` since that can cause issues with name space
2. We had 'from warnings import warn' but then things like 'warnings.warn("foo")' which need to be `warn.("foo")`
=> Cord trans

mbuild/compound.py, mbuild/tests/test_compound.py, mbuild/tests/test_coordinate_transform.py
Note: this slightly changes the gromacs saving behavior. Previously, specifying `.gro` or `.top` would save both. This "feature" has been removed and you will now only get the file that you specified.
Resolves #272
=> Cleanup forcefield application during saving

mbuild/compound.py, mbuild/tests/test_compound.py
Cloning of a Compound will fail if it contains bonds to Particles
that reside outside of the Compound's containment hierarchy (as
these Particles are not included in the clone). Rather than simply
raising a KeyError when the bond cloning fails, a more descriptive
error message is now provided.
A unit test has been added to check for this error message.
This resolves #321
=> Add more descriptive error when _clone_bonds fails

.travis.yml, environment.yml, mbuild/compound.py, mbuild/tests/test_compound.py
The PDB writer we are using from ParmEd does not write bonds, and since a temporary PDB file was being used in energy_minimization the bonds were being lost. OpenBabel was then inferring bonding from the atom spacing. The type of the temporary file has been switched to MOL2 which solves this problem.
As a side note, the bond order is still being inferred from the atom spacing.  This is something that a future PR may be able to fix by inferring bond order from the local chemistry.
=> Fix bug in energy_minimization where bonds were being interpreted incorrectly

mbuild/compound.py
I'm not sure if the wording is correct but you can either give mbuild a force field name or give it a force field file.
=> fixed ff save documentation and removed some trailing whitespace

mbuild/compound.py, mbuild/tests/test_compound.py
The charge attribute now returns either the partial charge on the Compound (if it resides at the bottom of the containment hierarchy) or the sum of the partial charges of all Particles a Compound contains.
A warning is now raised if a save() is called on a Compound that is not charge neutral.  The total charge on the Compound is checked after force field application (if one is specified).
This resolves #280
=> Changes to charge attribute and charge neutrality warning

mbuild/packing.py, mbuild/tests/test_packing.py
#253 and potential fix to #353
This would allow us to maintain both types of parent hierarchies (fluid-like systems to be built with ```mb.fill_box``` and protein-like solvation done with ```mb.solvate()```). However, there may be some cases in which calling ```mb.solvate()``` without making a new parent level would be desirable.
=> Allow fill_box to accept multiple compounds in one call

mbuild/compound.py, mbuild/tests/test_compound.py, mbuild/tests/test_gsd.py, mbuild/tests/test_hoomdxml.py, mbuild/tests/test_lammpsdata.py, mbuild/utils/io.py
A filename can be passed to the save function to output references for the force field that is being applied. References are written in BibTeX format.
This PR is identical to #335, but that PR was having some weird merge issue so it was easier to just open a new one.
=> Add arg to save() to output force field references

appveyor.yml, mbuild/compound.py, mbuild/tests/base_test.py, mbuild/tests/test_compound.py, mbuild/utils/io.py
ParmEd's PDB reader (and possibly other readers) infer bonds from inter-particle distances and standard residue templates.  This can lead to undesired topologies, such as in #362.  Reverting back to MDTraj's readers seems to be the best course of action for now, although the option to use ParmEd's readers is provided as this can be desired in certain cases (see #349 ).
=> Revert back to Mdtraj readers

mbuild/packing.py, mbuild/tests/test_packing.py
I was sloppy in #311 and I didn't catch the case of passing a list of ```mb.Box``` to ```fill_region```.
h/t @loganguy11
=> Fix passing list of mb.Box to fill_region

mbuild/examples/test_examples.py
Travis has been failing occasionally due to timing out on the examples tests.  Checking to see if increasing the wait time before timing out solves this issue.
=> Increase timeout for examples tests to 60 seconds

docs/index.rst
Avogadro link in the docs was dead. Updated to general landing page for Avogadro.
=> Fix 404 error with Avogadro Link

mbuild/packing.py, mbuild/tests/test_packing.py
Added rudimentary support support for specifying density while packing system.
* If passed ```n_compounds``` and ```density``` but no ```box```, it computes the size of a corresponding cubic box. This should currently work for multiple compounds.
* If passed ```box``` and ```density```, it computes the corresponding ```n_compounds ```. This currently does not work for multiple compounds.
* If passed ```box``` and ```n_compounds``` but not ```density (and after the above cases compute the missing variable) the packing proceeds as before.
Support I intend to add in the future:
* Aspect ratio for computed boxes, i.e. packing set quantities of compounds into a box with dimensions ```[L, 3L, L]```
* Composition ratio, i.e. packing ethane and water into a box of set size at a 2:1 ratio
=> Add density as an argument to fill_box

mbuild/compound.py, mbuild/tests/test_compound.py
An argument has been added to `Compound.save()` allowing the user to specify the combining rule used for nonbonded interactions (either `'lorentz'` or `'geometric'`, for Lorentz-Berthelot or geometric combining rules, respectively).
This should resolve #358
=> Add argument to save() to specify combining rule

mbuild/box.py, mbuild/coordinate_transform.py, mbuild/tests/test_box.py
Currently, many tests build boxes to include integer arrays.
```
>>> import mbuild as mb
>>> box = mb.Box([4, 4, 4])
>>> box.maxs.dtype
dtype('int64')
```
These changes force `Box.maxs`, `Box.maxs`, and `Box.lengths` to be `dtype=np.float64`.
I know we have discussed a more thorough rework to the `Box` class at some point in the future, but this is important change to fix now. Even though it is minor.
=> Force box values to np.float

.travis.yml, appveyor.yml, requirements.txt
There is currently an issue where homebrew will always fail due to an
issue with ruby. Forcing homebrew to update before installing any
packages fixes this issue.
=> Fix Ruby 2.3 homebrew issue

.travis.yml, requirements.txt
Currently all python 3.5 osx builds on Travis are
failing at the collection stage of pytest due to
a SIGABRT signal being raised.
We currently do not have a way to interpret where this
is occuring since we cannot replicate on any osx 3.5
machines in the office.
There is a pytest plugin called `pytest-faulthandler` that
enables the `faulthandler` module for pytest.
This should provide a more verbose output when the system recieves
a signal like this in the future.
=> Provide segfault trace for pytest

mbuild/lattice.py
When populating lattice, there will occasionally
be values near 0 that exhibit rounding errors that
push the values to very small scientific notation
(1e-16+, etc) representation. 
This is not the most accurate and
rounding back to 0 after a threshold "tolerance"
value (1e-12) is reached is desired.
=> Floating point rounding fix for lattice.populate

.travis.yml, appveyor.yml, devtools/conda-recipe/meta.yaml, mbuild/examples/test_examples.py, requirements.txt
Discovered in #390 there seems to be a timeout issue with the Jupyter notebook tests. It looks like MDTraj ran into a similar issue and resolved it in mdtraj/mdtraj#1315 by using [pytest-ignore-flaky](https://pypi.python.org/pypi/pytest-ignore-flaky) to mark these tests as flaky and ignoring if they fail. @justinGilmer and I have implemented a similar fix here.
=> Marking examples tests as flaky

docs/conf.py, docs/sphinxext/notebook_sphinxext.py, mbuild/compound.py
In #334 a check was added within the `energy_minimization` routine to ensure all particles featured a proper element name (otherwise OpenBabel would return a not-so-helpful error). However, this check added a dependency on OpenMM which was not added to the conda build recipe. I've fixed this here by replacing the "element check" we were using OpenMM for with an equivalent check that uses MDTraj.
=> Use MDTraj to check element existence instead of OpenMM

docs/citing_mbuild.rst, docs/files/mbuild_citation.bib, docs/files/mbuild_citation.ris, docs/index.rst
An additional tab has been added to the website that details how to properly cite mBuild. A link to the mBuild paper is provided alongside ACS and BibTeX citations. Downloadable BibTex and RIS
files are also included.
=> Add information to website concerning how to cite mBuild

mbuild/compound.py
In #416, `from foyer import Forcefield` was added to the top of `compound.py`. This ends up leading to issues with a dependency loop where the following occurs if trying to import Foyer (having both the latest development versions of mBuild and Foyer):
```
>>> import foyer
Traceback (most recent call last):
File "<stdin>", line 1, in <module>
File "/Users/summeraz/src/github/mosdef-hub/foyer/foyer/__init__.py", line 1, in <module>
from foyer.forcefield import Forcefield
File "/Users/summeraz/src/github/mosdef-hub/foyer/foyer/forcefield.py", line 17, in <module>
import mbuild as mb
File "/Users/summeraz/src/github/mosdef-hub/mbuild/mbuild/__init__.py", line 2, in <module>
from mbuild.coarse_graining import coarse_grain
File "/Users/summeraz/src/github/mosdef-hub/mbuild/mbuild/coarse_grainin …
```
=> Move `Forcefield` import into `energy_minimize` method

mbuild/lattice.py, mbuild/tests/test_lattice.py
Alpha beta angles were swapped
When generating a lattice that is non-rectangular in the alpha and beta
dimensions from provided lattice_vectors, the alpha and beta bravais
angles would not be in the correct order.
Expected
lattice.angles returns [alpha, beta, gamma]
actual
lattice.angles returns [beta, alpha, gamma]
There was an incorrect array access that caused this issue.
Credit to @witteaj  for spotting this issue when working with triclinic lattice systems.
=> Lattice hotfix

mbuild/box.py, mbuild/compound.py, mbuild/formats/gsdwriter.py, mbuild/formats/hoomdxml.py, mbuild/formats/lammpsdata.py, mbuild/tests/test_box.py, mbuild/tests/test_compound.py, mbuild/tests/test_gsd.py, mbuild/tests/test_hoomdxml.py, mbuild/tests/test_lammpsdata.py
The `Box` class has not been touched in a while and needs some additions.
The scope I plan to include
~~- [ ] Fix for #365~~
I am not planning to add `box` attribute to `mb.Compound`.
Note that unless we want to move `Compound.periodicity` into a `Compound.box` attribute, the `from_parmed` and `from_trajectory` functions will not read angle information in.
=> Improvements to Box class

mbuild/formats/lammpsdata.py
After #448, box coordinates in LAMMPS data files are being written in nm instead of Angstroms. This fixes that.
Not that an alternative solution would be to simply not convert from Angstroms to nm when converting `structure.box` to `mb.Box` [here](https://github.com/mosdef-hub/mbuild/blob/0cdb42f1b10dcccb1eaf227df00e14cd831394b8/mbuild/formats/lammpsdata.py#L55). However, while it should work and use a couple fewer characters of code, I think it is bad practice to use inconsistent units internally.
=> Write LAMMPS box values in angstroms, not nm

appveyor.yml, changelog.md
This at least gets it to build the conda package ([before](https://ci.appveyor.com/project/mattwthompson/mbuild/builds/20932129) and [after](https://ci.appveyor.com/project/mattwthompson/mbuild/builds/20932552)). Not sure about the tests at the moment.
=> Run `activate base` before `conda build` in Appveyor

.gitignore
Using Microsoft's VSCode generates an addtional directory
and files to assist the various plugins, save states, etc.
This is not needed for other users.
This has been added to the .gitignore file to prevent these files from
being committed erroneously.
=> Update gitignore file for VSCode

.travis.yml, appveyor.yml, changelog.md, devtools/conda-recipe/meta.yaml, mbuild/compound.py, mbuild/packing.py, mbuild/tests/test_compound.py, mbuild/tests/test_gsd.py, mbuild/tests/test_hoomdxml.py, mbuild/tests/test_lammpsdata.py, mbuild/utils/io.py, requirements-dev.txt, requirements.txt, setup.py
We've had issues with a dependency loop due to `mbuild` and `foyer` both having each other as a required dependency. To fix this, and to make MoSDeF more modular, this PR separates `foyer` out as an optional dependency, though still required for development and testing.
To specify that `foyer` is required for testing, this PR also separates out from our `requirements.txt` file a `requirements-dev.txt` file that lists all packages required for development and testing of `mbuild`. `requirements.txt` now contains only the subset of packages that are required to actually use `mbuild`.
=> Update dependency requirements

changelog.md, mbuild/formats/hoomdxml.py, mbuild/tests/test_hoomdxml.py
This creates a new parameter for `write_hoomdxml` that enables automatic scaling for reference values of mass, energy, and distance. When saving, we also return a named tuple so these auto values can be used programmatically.
=> fixes issues #437

mbuild/formats/lammpsdata.py
The format that `lammpsdata.py` was writing out triclinic box coordinates was previously incorrect.  Correcting this now allows for Lammps data files with triclinic boxes to be loaded.
=> Fix triclinic box coordinates for Lammps

CONTRIBUTING.md
This is largely based off of [HOOMD's CONTRIBUTING.md](https://github.com/glotzerlab/hoomd-blue/blob/maint/CONTRIBUTING.md) and in the spirit of small PRs I opened it separately instead of adding it to #498, even though they tie in to each other.
* Do we want one for each package or one for the entire project (or both)?
* What other code standards do we want to suggest?
You can see the rendered markdown on [my fork](https://github.com/mattwthompson/mbuild/blob/contributors-guide/CONTRIBUTING.md)
=> Draft of a contributors guide

.github/ISSUE_TEMPLATE/BUG_REPORT.md, .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md, .github/ISSUE_TEMPLATE/QUESTION.md, .github/PULL_REQUEST_TEMPLATE.md
This adds a `.github/` folder, which includes templates for PRs and issues. Most is relatively boilerplate, a few important points are:
* The way I structured the issue template allows people to choose between three templates (see [here](https://github.com/MDAnalysis/mdanalysis/issues/new/choose) for how it actually looks from the user's end). This is because "issues" here are really a mix of bug reports, feature requests, usage questions, and other discussions.
* We should probably think about start a contributor's guide. This doesn't need to be big, but establishing some style/linter guidelines (I like PEP8 but I never want to be 100% compliant), showing a MWE, etc.
* If we like this, or something like this, I can do the same thing for foyer. But a contributor's guideline may be better …
=> Add some issue/PR templates

README.md
Now that we have a gitter channel, we need to make it easily accessible from the github repos.
=> Add gitter badge for mosdef-hub/Lobby 

mbuild/packing.py
This PR removed an un-used internal function accidentally left in as a result of some conflicting packing-related PRs. It was not called at all in [testing] and, as a consequence, cheated us out of a fraction of a percent of coverage.
------------
=> Remove unused internal function

.travis.yml, appveyor.yml
This PR drops the `glotzer` and `bioconda` channels from the testing scripts. Each channel previously included dependencies that are now hosted on `conda-forge`. The `glotzer` channel was used for `gsd` (#489) and `bioconda` was used for `nglview`.
------------
=> Drop glotzer and bioconda channels

mbuild/tests/test_lammpsdata.py
This PR adds a `@pytest.mark.skipif` that was preventing me from packing a release with conda. See two tests earlier in this file for context; missing this one was oversight and this change is a patch. It was not found on CI because CI uses `requirements-dev.txt` and (it seems) `conda build` does not.
------------
=> Skip a test that requires foyer

mbuild/utils/io.py
Glotzer group doesn't maintain their conda channel and instead use `conda-forge`
------------
- [x ] Includes appropriate unit test(s)
- [ x] Appropriate docstring(s) are added/updated
- [x ] Code is (approximately) PEP8 compliant
=> Use conda-forge instead of the glotzer channel

README.md
Our README badge for Gitter was a `png` file, which rendered in low quality on higher fidelity screens. This update uses a vector graphic `svg` instead, which scales based on resolution. 
------------
=> Use vector image for the gitter badge

mbuild/compound.py, mbuild/tests/test_compound.py
Raise ValueError when access non-existent port
Raise a ValueError when accessing Port that does not exist responding to issue #505 and #509. 
------------
=> Raise ValueError when access nonexistent Port

mbuild/compound.py
Using py3dmol to visualize compounds, the image appears twice - we call `view.show()` which will show the image, but the returned object will also appear in a jupyternotebook. I think the most appropriate fix is to remove the `view.show()` call
EDIT: I'm using this PR to squash miscellaneous bugs in py3dmol visualization
This PR addresses the use of py3Dmol and showing duplicate images in jupyternotebooks. The issue was an additional `show` method being called. Very minor bugfix
------------
=> Remove duplicate visualization in py3dmol

mbuild/compound.py
Enforce uppercase,lowercase formatting for element abbreviations
(Si, not SI, Cl not CL).
When converting a `Compound` to a `ParmEd` structure using the
`Compound.to_parmed()` method, there is a lookup section to
infer the elements present in the compound. If the element names are
fully capitalized (which can happen when reading in from certain mol2
files, and others), the inference does not correctly determine the
chemistry. In the above examples SI would be inferred as Sulfur (S), and
CL would be inferred as Carbon (C).
This can induce issues when trying to go from an mBuild Compound, to
a ParmEd structure, to an atomtyped system using Foyer.
This is not a catch-all fix, as non-elemental names that are not
prefaced with an underscore (which they should be, but sometimes this is
missed …
=> Enforce captialization standards in to_parmed()

appveyor.yml, devtools/conda-recipe/meta.yaml
Might fix #552. The problem was `ipyext` was still in the conda recipe and it has not been updated for [years](https://anaconda.org/janschulz/ipyext/files) and lacks a version with Python newer than 3.5, so when it tried to install dependencies it was forced to downgrade to Python 3.5. We have the tests marked as flaky (note this is only relevant to pytest, not conda) and are not installing them with Travis.  Because Travis just installs the package from source and does not try to `conda build` it and we only interact with `conda build` when packaging, this bug went unnoticed. We also made some changes to the Appveyor recipe to be more verbose so we can better understand logs in the future.
------------
=> Update Appveyor configuration

mbuild/formats/lammpsdata.py, mbuild/tests/test_lammpsdata.py
Addressing #568, the proper residue indices are being written out to the LAMMPS data files.
------------
=> Print out residue indices to lammps data file

requirements-dev.txt
This morning, @joaander bumped GSD from 1.7 to 1.8, which dropped Python 2.7. This, in my opinion, is enough reason to stop supporting Python 2.7 (see #479). However, to make one final release that does, we need to pin GSD to 1.7. Normally we might not have to, but something was weird in GSD's conda recipe that built a 1.8-py27 version on anaconda.org despite it not being supported (Josh said he is looking into it)
------------
=> Pin GSD to 1.7 for Python 2.7 support

.travis.yml, docs/installation.rst, requirements-dev.txt, setup.py
Officially dropping Python 2.7. I have tried to remove it from CI and docs but it is likely I missed a file or two. Python versions are not specified in the conda instructions and we already dropped it in Appveyor.
#572 #479
------------
=> Drop Python 2.7

.gitignore
Since adding support for protobuf as a way to serialize mb.Compounds,
the `protoc` compiler will generate a python file `compound_pb2.py`.
This file is not to be included in version control, since it is
generated on the user's machine.
This commit adds the `protoc` compiled `compound_pb2.py` file to the
gitignore to minimize confusion for anyone unfamiliar with protobuf.
Addresses #601 
------------
=> Update gitignore for protobuf generated file

mbuild/coarse_graining.py
Fixes #603 by changing how we name proxy "compounds." Previously we appended ` (proxy)` to the name but that was causing issues when writing and then reading to MOL2 files (note that this was because of space, not the parentheses). We tested this by visualizing the CG hexane notebook using `backend='nglview'` and it worked. This might hopefully prevent other issues related to saving CG systems to MOL2 from popping up.
------------
=> Change how we label proxies in their compound names

mbuild/compound.py
Fixes #575. Obviates the need to install Openbabel, which is not a required package.
------------
=> Fixed unnecessary pybel import in mb.load()

mbuild/compound.py, mbuild/tests/test_compound.py, mbuild/utils/io.py
Fixes #607 (I hope). From what we can tell so far, the only breaking change to openbabel 3.0.0 is how `pybel` is imported. It looks like if we replace `import pybel` with `from openbabel import pybel` we can continue. This PR proposes a clause in `import_` that does this checking and imports `pybel` in the appropriate manner by checking each. I have tested this locally with both openbabel versions. The advantage to this approach is that we might not need to pin or enforce openbabel versions; the downside is that the code is a little ugly and it might not cover all breaking changes.
------------
=> Try to import pybel in a openbabel 2/3 compatible manner

mbuild/formats/par_writer.py
There were a few extra imports in the PAR writer. While nothing more than un-used code here, it seems (:tm:) to have accidentally produced a circular import when foyer tries to import mbuild. It doesn't make sense to me that the `from foyer import Forcefield` line would be executed upon importing mbuild when inside foyer, but this change fixes that issue for me (at least locally). This (hopefully) fixes some downstream issues when `has_mbuild` evaluated to `False` in foyer, issues that were a headache today when testing foyer after mBuild 0.10.0.
An important note here is that **we should never directly import foyer** (`import foyer`/`from foyer import Forcefield`) inside of mbuild. If needed, this would be the necessary approach:
```
foyer = import_('foyer') 
myff = …
```
=> Remove a few un-used imports that might produce circular issues

mbuild/tests/test_compound.py
I just wanted to take a quick stab at reducing the length of some of our unit tests, particularly the longer ones.
<details><summary>Before:</summary>
<p>
```
=================================== slowest 20 test durations ===================================
41.93s call     mbuild/tests/test_compound.py::TestCompound::test_from_pybel_monolayer
15.81s call     mbuild/examples/test_examples.py::test_examples[mbuild/examples/solvate/solvate.ipynb]
8.83s call     mbuild/tests/test_compound.py::TestCompound::test_save_residue_map
4.97s call     mbuild/tests/test_compound.py::TestCompound::test_save_forcefield
4.86s call     mbuild/examples/test_examples.py::test_examples[mbuild/examples/pmpc/pmpc_brush_layer.ipynb]
4.44s call     mbuild/tests/test_silica_interface.py::TestSilicaInterface::test_se …
```
=> Reduce the length of some unit tests

azure-pipelines.yml
This patch tries to install `pytest-azurepipelines` using pip.
=> Try to install pytest-azurepipelines. Closes #637

mbuild/formats/par_writer.py
When parmed writes a PAR file for CHARMM simulations, the keyword is `IMPROPERS`. However, PAR files for NAMD/GOMC use the keyword `IMPROPER`. This PR defaults the mbuild par-writer to using `IMPROPER`
------------
=> Change keyword for par file

mbuild/compound.py
Fixes #652 
In an environment that does not have `networkx` (which is currently treated as a test-only requirement), you cannot `import mbuild` on the `master` branch, but you can with these changes.
I did not update the MCF tests because they already depend on `networkx` via `foyer`.
------------
=> Only import MCF writer if networkx is installed

devtools/conda-recipe/meta.yaml
Add `nbval` as requirement for conda built testing.
------------
=> Add nbval as test requirement for conda build

mbuild/tests/test_utils.py, mbuild/utils/geometry.py
This PR introduces a utility function to wrap XYZ coordinates into a specified box, assuming positive octant. This helps for creating structures + XYZ within HOOMD libraries
------------
=> Wrap coordinates function

mbuild/formats/hoomd_snapshot.py, mbuild/tests/test_hoomd.py, mbuild/utils/reference/lj.xml
For systems with no bonds, creating a hoomd snapshot will error because it will try to cast an empty list into a multi-dimensional numpy array. This PR is a quick fix to ensure there are bonds, angles, or dihedrals before trying to do any shape-casting
=> Don't populate empty lists for hoomd snapshot

.travis.yml
The recipe we inherited includes a `brew install md5sha1sum` step to check the hash of what we installed. At some point in time (I will not investigate this) this may have gotten merged into macOS (see [1](https://stackoverflow.com/a/57133600/4248961)) and [below](https://api.travis-ci.org/v3/job/628478750/log.txt)). My first guess of simply removing the above install line seems to have worked on my fork ...
```
[0K$ if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install md5sha1sum; fi
==> Downloading https://homebrew.bintray.com/bottles/md5sha1sum-0.9.5_1.high_sierra.bottle.tar.gz
==> Pouring md5sha1sum-0.9.5_1.high_sierra.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/md5sum
Target …
```
=> Fix travis by not installing md5sha1sum

mbuild/formats/cassandramcf.py
Current MCF writer fails for systems with no bonds defined. Cassandra supports species with zero defined bonds when all the atoms are held fixed (e.g., adsorption in solid frameworks). This fix allows MCF files to be written in such cases. 
------------
=> MCF support for systems with no defined bonds (e.g., solid frameworks)

mbuild/lattice.py, mbuild/tests/test_lattice.py
Addresses #465 with my proposed idea of a second function; would look something like this in practice:
```python3
mylattice = mb.Lattice(...)
mycompound = mylattice.populate(x=10, y=10, z=4)
mybox = mylattice.get_populated_box(x=10, y=10, z=4)
```
Things I suggest considering when reviewing
* Does this look okay from the user's perspective?
* What other tests should we consider? `_sanitize_populate_args ` is already tested in `populate` but I didn't consider edge cases
* How to handle non-rectangular boxes? Just punt?
------------
=> Add a function that returns a "populated lattice" box

mbuild/formats/gsdwriter.py, requirements-dev.txt
Fix bug related GSD 2.0.0 release per #680. Replace `gsd.hoomd.create` with `gsd.hoomd.open`. 
------------
=> update gsd deprecated syntax

mbuild/box.py, mbuild/formats/lammpsdata.py, mbuild/tests/test_box.py
Patches for #365. Makes `box._lengths`, `box._maxs` and `box._mins` to be "immutable". You still can change mins, maxs, and lengths by `box.mins = [1, 1, 1]` (which go through the `settter` method), but `box.mins[0] = 1` will return a `ValueError`.
------------
=> Allow single dimension setter for mb.Box class

mbuild/compound.py, mbuild/tests/test_box.py
The bleeding mbuild tests were failing on a foyer PR due the the assertion error that the `mins` of the mb.Box were greater than the `maxs`.  
The source of this was due to the way we currently handle mBuild compounds with no Box information.  In this case, we first initialize a box by calling `boundingbox`, which simply returns a box based on the minimum and maximum coordinates of the compound.  The issue is that after this, we set `box.mins` to `[0, 0, 0]`.  In the case of the failing test, `box.maxs` had negative coordinates due to calling `self.boundingbox`.
I think we can avoid this assertion error if we first set `box.maxs` first and then `box.mins`.  That way, we can ensure that the max coordinates are greater than the min values.
------------
=> Switch order that box mins and maxs are set

MANIFEST.in
This pull request adds the `LICENSE.rst` file to `MANIFEST.in`. This means that all wheels and source distributions created for `mbuild` will include the license. We need this to be able to package on conda-forge: https://github.com/conda-forge/staged-recipes/pull/10975
------------
=> Include LICENSE.rst in MANIFEST.in.

mbuild/compound.py, mbuild/tests/test_compound.py
This PR is to fix a bug in `to_parmed` which relates to the new `mb.Box` class. 
This bug (found by @rmatsum836) happens when we trying to convert a mb.Compound to a pmd.Structure. During one step, we create a box based of Compound `self.boundingbox`, and try to re-set it maxs and mins. If the new maxs (or mins) is smaller (or greater) than the one already in that box, we have an error raised by one of our sanity check.
------------
=> Fix Box related bug in to_parmed

mbuild/formats/par_writer.py
Fixes the problem of par_writer.py outputing rmin/4 instead of rmin/2.  Parmed stores rmin/2 in "rmin", so no additional division by 2 is needed when writing values to the CHARMM-style parameter file.
------------
=> fix factor of 2 error in rmin/2

docs/data_structures.rst, docs/recipes.rst
In the `Data Structure` section of our documentation, we did not have
the `mbuild.Box` class represented.
The docstrings were there, but the rst files did not include them.
The Lattice class was also in the `Recipes` section of the docs, but
better fits in the Data Structure section.
------------
#700
=> Include Box and Lattice in Data Structure docs

mbuild/tests/test_utils.py, mbuild/utils/io.py, requirements.txt
Currently we hard require `nglview` for all `mBuild` installs, which
brings along a lot of `ipython` and other `jupyter` dependencies.
These are only ever used when running `ipython` instances and wanting to
visualize a `Compound`. It seems reasonable to migrate this to a soft
dependency, and inform the user if they try to `visualize` that they
need to install `nglview` or `py3Dmol`.
We have not tested if our `run_from_ipython` method returns what we
expect, although I have never ran into an issue where it has even
behaved in an unintended manner. A test has been added to at least check
if an environment is not an ipython env.
This should also minimize the dependencies of `mBuild` for a regular
installation.
------------
=> Remove `nglview` as a hard dependency

mbuild/pattern.py, mbuild/tests/test_pattern.py
In the `SpherePattern` class, `n` is assumed to be an integer value for
the number of points on a sphere. However that was not enforced. This
could lead to floating point math issues with the numpy `arange`
function. See issue
[467](https://github.com/mosdef-hub/mbuild/issues/467) for a more
detailed disucssion.
This patch typecasts `n` to an integer when passing to `numpy.arange`.
This appears to prevent floating point overflow, preventing NaNs for the
generated points on the SpherePattern.
------------
Closes #467
=> Typecast float to int to prevent NaNs in np.arange

mbuild/box.py, mbuild/lattice.py
The examples in the Lattice docstring were not properly formatted, new
lines were separated into multiple example blocks, when they should have
been a single box.
This has been updated by including newlines using the example numpydoc
syntax.
The Box class was also missing a definition for the angles
parameter/attribute, this has been updated.
A spelling mistake in the `BoxArray` class was also fixed.
------------
=> Data structure update

mbuild/formats/cassandramcf.py, mbuild/tests/test_cassandramcf.py
Changes concurrent with release of Cassandra-1.2.2
which supports up to six characters for element
names and twenty characters for atom names.
=> Update element name and atom type name lengths

Dockerfile, README.md, azure-pipelines.yml, docs/docker.rst, docs/index.rst
This PR addresses #727, By adding dividing azure-pipeline into two stages:
1. Test: Runs all the tests as is
2. Docker: Does the docker build and publish image (`mosdef/mbuild:latest`)(If the tests pass and the branch is `master`). 
To Dos:
1. Add docker service connection for logging into `mosdef` docker account. This should be done in azure pipeline settings.
Also, the current Image size is around 2.79 GB in my machine. That should be reduced to a sustainable size.
=> Build and Publish Docker Image (latest) to dockerhub (Closes #727)

mbuild/tests/test_protobuf.py, mbuild/utils/io.py
Relate to #697. Basically, this PR will add the `has_protobuf` variable, which will allow us to skip the `protobuf` unit test if the package is not installed. 
------------
=> Add has_protobuff variable

mbuild/compound.py, mbuild/utils/io.py
Closes #706.
* Update openbabel import to avoid import deprecation warning
* Add ignore_box_warn flag to from_pybel so that the
no box present warning can be ignored when creating
an mbuild.Compound from a SMILES string
------------
=> Fix unnecessary warnings when load from SMILES

mbuild/compound.py, mbuild/formats/lammpsdata.py, mbuild/tests/test_lammpsdata.py
LAMMPS boxes do not need to be centered at the origin or run [0,0,0] to [Lx,Ly,Lz]; min and max values for each dimensions are explicitly set in the data file (xlo xhi, ylo yhi, zlo zhi). 
The way the writer was written, an mbuild Box was defined with the function based on  the total length in each dimension, extracted from the parmed structure object. Since this parmed object doesn't not contain min and max info, only total length,  box dimensions were written out as [0,0,0] to [Lx,Ly,Lz]. The system coordinates were not shifted such that the system COM is placed at [ Lx/2, Ly/2 Lz/2]).  While this is just a minor inconsistency in terms of spatial location for periodic systems (although annoying when trying to convert between formats), this can fundamentally break a non-periodic system …
=> lammpsdata writer is now passed min and max box info

mbuild/compound.py, mbuild/tests/test_compound.py
Adds a `Compound.box` attribute (see #707 and #735). This PR only adds the attribute and basic unit tests. `Compound.periodicity` is still fully independent and functional. 
Port particles are explicitly prevented from having a `Compound.box` attribute.
A follow-up PR will map `Compound.periodicity` -> `Compound.box.lengths` and replace core `Compound.periodicity` usage with `Compound.box`. 
------------
=> Add Compound.box attribute

mbuild/formats/cassandramcf.py, mbuild/tests/test_cassandramcf.py
It was brought to my attention that the fragment identification did not work properly in the cases of more complex ring systems: e.g., this cage molecule here:
This PR updates how fragments are identified for fused/merged rings and adds unit test for two cases, naphthalene, and then one of these cage-type structures.
------------
=> Fix MCF fragment identification for more complex ring systems

mbuild/compound.py, mbuild/tests/test_compound.py, requirements-dev.txt
Fixes #752 
* Makes sure that the clone's children are set before setting it's box
* Adds tests for clone, and visualize
------------
=> Fix bug in cloning compound with box

devtools/conda-recipe/meta.yaml
To ensure that we have our plugins supported properly when installed
from conda, it appears that a few options are necessary to ensure that
is the case.
For the case of setuptools entry_points, the conda-build documentation
recommends that we do include the build option: preserve_egg_dir
https://docs.conda.io/projects/conda-build/en/latest/user-guide/recipes/build-without-recipe.html#preserve-egg-directory
Setuptools are also now build and runtime dependencies.
------------
=> Support entry_point plugins with conda

mbuild/lattice.py, mbuild/tests/test_cif.py, mbuild/utils/io.py
Thanks to a catch by @uppittu11, the `pycifrw` package was not being
properly tested for an import error, this has now been fixed.
Previously, the `pycifrw` package was conditionally imported using
`import_('pycifrw')`, this is not the module name for `pycifrw`, it is
actually `CifFile`. This change has been made in both the cif reading
logic as well as the tests.
Also, two tests were being skipped always in `test_cif.py`, this was due
to a capitalization error in the `has_garnett` module in
`mbuild.utils.io`.
This has also been fixed.
------------
I recommend a release of mBuild once merged.
=> Properly test and import the correct CIF modules

mbuild/lattice.py
Currently, when creating a `Lattice` from a CIF file, the information
that is used to construct the lattice is the `box_matrix` from the
Garnett CIF reader.
The box_matrix has the a,b,c vectors of the lattice arranged in a
columnar format:
| ax | bx | cx |
| --- | --- | --- |
| ay | by |cy|
| az | bz |cz|
The a vector is the first column, b the next, etc.
mBuild constructs its Lattice's with a box matrix in row-ordered
formatting, which is the transpose of the above matrix.
The transpose was never completed before constructing a lattice, which
led to numerous issues regarding the lattice dimensions.
This fix transposes the matrix before being passed to the `Lattice`
constructor.
This PR closes #766 
------------
=> Include missing transpose of cif box_matrix

mbuild/lattice.py, mbuild/tests/base_test.py
Previously, when handling degrees and radians within mbuild, we defined
a conversion term (180 / pi) or (pi / 180) to convert radians to degrees or
degrees to radians, respectively.
Ryan (@rsdefever) mentioned in passing that numpy already has methods to
handle this conversion for us: `np.rad2deg` and `np.deg2rad`.
All instances where conversions between degrees and radians were needed
are now using these methods.
------------
=> Use numpy conversions

requirements-dev.txt
If people installing all the requirements from `requirements-dev.txt` and not have their conda channel in the correct order, an old version of `openbabel` (2.4) will be (more than likely) be pulled from `ominia` and break mbuild. This PR will pin the `openbabel` to the more recent working version (>=3.0.0), so the user can still pull the working version even if the conda channel is in wrong order. 
------------
=> Pin Openbabel to 0.3.0

mbuild/conversion.py
Currently, after the overhaul of the load functionality, there was a
small syntax error introduced during a condition where a ValueError was
raised.
This has now been fixed, as well as providing a slightly more
descriptive error message.
------------
=> Fix syntax error in conversion.py

mbuild/packing.py, mbuild/tests/test_packing.py
Relate to this #762 and #446. Add `sidemax` as an argument for various packing functions so user can build larger box/sphere. 
------------
=> Add sidemax as argument for various packing functions

mbuild/compound.py
Fixes the following warning:
```
/Users/ryandefever/repos/mosdef/mbuild/mbuild/compound.py:9: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
from collections import OrderedDict, Iterable
```
=> Fix deprecation warning on 'Iterable' import

mbuild/compound.py, mbuild/conversion.py, mbuild/formats/compound.proto, mbuild/formats/json_formats.py, mbuild/formats/protobuf.py, mbuild/formats/xyz.py, mbuild/tests/test_compound.py, mbuild/tests/test_json_formats.py, mbuild/tests/test_xyz.py
Initial integration of element attribute into conversions. This includes to/from conversions for:
* pybel
* parmed
* mdtraj
Removes reliance on `parmed` and `mdtraj` periodic table except when converting to/from those data structures.
How do we handle inference?
* Check if `Compound.name` is an exact match to the two-character element code
* Check if `Compound.name` is an exact match to a full element name (e.g., calcium)
* Otherwise default to no element (atomic number, mass = 0, parmed="EP")
**Examples**: see [here](https://gist.github.com/rsdefever/8d57910f6a00101c953889fcc3ad3e16) for a notebook with some examples to test out the functionality!
Tests passing locally at the moment. Need to add more tests and consider integration with writers.
------------
=> Integrate element attribute with object conversions and writers

mbuild/lattice.py, mbuild/tests/test_cif.py, mbuild/utils/reference/LaCl3.cif, mbuild/utils/reference/ReS2.cif
Previously, when loading in from a cif file, the Lattice object used the
Box.Lx, Box.Ly, Box.Lz from the garnett trajectory; this value was in
euclidean space, not lattice space (which is what the lattice object
operates in).
This oversight would lead to discrepancies when loading in a cif file
versus building the same lattice object manually. Now, the lattice-space
lattice spacings are correctly set when loading a cif file.
This matches current manual lattice behavior.
An additional test is now included to ensure that whether building
manually, or from a cif file, that the lattice objects are functionally
equivalent.
------------
Resolves #818
=> Use correct lattice spacing when reading from cif

mbuild/formats/lammpsdata.py, requirements-dev.txt, requirements.txt
See https://github.com/ParmEd/ParmEd/pull/1122 for the order change of the `nbfix_types` in newer version of `parmed`.
=> Update nbfix_types index changes in parmed

mbuild/box.py, mbuild/periodic_kdtree.py, mbuild/tests/test_box.py, mbuild/tests/test_coordinate_transform.py
This PR updates some types that are now deprecated as of NumPy 1.20, released last weekend. To reproduce:
```shell
$ python -c "import mbuild; mbuild.Box([4, 4, 4])"                               240b30c7  ✱
/Users/mwt/software/mbuild/mbuild/box.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
lengths = np.array(lengths, dtype=np.float)
```
Or run `pytest -v | grep DeprecationWarning`. These warnings annoyingly trigger when the box class is imported. For more: …
=> Remove deprecated aliases from NumPy to built-in types

mbuild/packing.py
Addresses issue #836 
Previously, `fill_box` and `fill_regions` in `packing.py` would only adjust the maximums of the box used by PACKMOL during packing. As a result, the packed compound would only have buffers on 3 of the 6 faces of the box or region.
I added a couple lines that makes the same adjustment to the minimums of the box. 
------------
=> Fix edge adjustment to include box minimums

mbuild/formats/cassandramcf.py, mbuild/tests/test_cassandramcf.py
Closes #813 and adds the relevant unit test.
The MCF writer tries to infer the 1-4 scaling factors from some of the data in the `Structure.adjusts`. However, if one of the `epsilon` values is `0.0`, this results in a division by zero, and an error. An example molecule is methanol, where the `H` on the `O` has zero epsilon and the 1-4 interaction is between that and the `H` on the carbon.  
------------
=> Fix 14-scaling inference if one atom has zero epsilon

azure-pipelines.yml
Uploading `codecov` reports without using tokens.
=> Remove '--no-coverage-upload flag', does not exist anymore

mbuild/tests/test_compound.py, mbuild/utils/io.py
Importing mbuild was giving an error in jupyter when the nglview labextension was not installed. Fixes #840 
"Error displaying widget: model not found"
It was coming from the has_nglview variable in mbuild/utils/io. This PR just moves that variable to the test where it is used.
------------
=> Silence Jupyter Error

mbuild/compound.py, mbuild/conversion.py, mbuild/tests/test_compound.py
Previously, (h/t to @jennyfothergill) our `intermol` converters had
silently been skipping their unit tests, this has now been fixed.
There was some malformed logic in some of the tests when converting an
`mbuild.Compound` to an `intermol.System`. This was due to a few
factors, where the `molecule_types` function argument was always being
set to `None` and not the user-provided values. This caused issues when
naming and distinguishing different `Compounds` during conversion. Also,
to determine if the correct number of bonds were present for each
`molecule_type`, you have to access the `bond_forces` for that
`molecule_type`, which was being incorrectly called.
NOTE: The `#pragma no cover` has not been removed, but testing should be happening again.
------------
Tangentially closes #399
=> Intermol fixes

Dockerfile
Fix line continuation error in Dockerfile. Docker cannot build the image without this addition.
------------
=> Fix line continuation error in Dockerfile

azure-pipelines.yml
Now that mbuild and foyer are both using conda ymls, we need to update the way the bleeding test environment is created in azure pipelines for mbuild. I used conda-merge and followed the same method as in https://github.com/mosdef-hub/foyer/pull/400
------------
=> Update bleeding test environment

mbuild/packing.py, mbuild/tests/test_packing.py
It looks like I missed the `solvate` function when fixing the edge buffer being applied to the box mins in #837.  This PR adds the same fix that was used in `fill_box` and `fill_region`. Also, I added a unit test that tests that the buffer is working as expected for each of the packing functions.
------------
=> Fix edge buffer for solvate in packing.py, add edge unit test

docs/sphinxext/notebook_sphinxext.py, mbuild/coarse_graining.py, mbuild/compound.py, mbuild/conversion.py, mbuild/coordinate_transform.py, mbuild/formats/compound.proto, mbuild/formats/lammpsdata.py, mbuild/formats/protobuf.py, mbuild/lib/surfaces/amorphous_silica_surface.py, mbuild/pattern.py, mbuild/tests/test_compound.py
- all TODO comments were removed and converted to issues.
Fixes #872 
------------
=> Remove TODO comments

Dockerfile
After testing @rmatsum836 's [dockerfile update for gmso](https://github.com/mosdef-hub/gmso/pull/537) I realized that our conda environment.yml files do not contain `jupyter` which is necessary for our docker images. This patch installs jupyter after the `mbuild-dev` env has been created. 
------------
=> Install jupyter so the entrypoint does not fail

mbuild/formats/xyz.py, mbuild/tests/test_xyz.py
Right now the `xyz` writer writes the `atom.name` attribute from the `parmed.Structure` to the first column of the `xyz` file. This PR changes the default behavior, so the `atom.element_name` attribute is written. A `write_atomnames` boolean argument is added to `write_xyz` that flips back to the original behavior (where `atom.name` is saved instead).
The motivation for this PR is two-fold:
* Bring the behavior of our xyz writer into better alignment with our `xyz` reader
* Fix the following quirk: `mbuild.Compound` -> `.xyz` -> `mbuild.Compound` will lose the element information unless the `Compound.name` is the same as the two character element code. Of course now we'll lose the `Compound.name`, but that seems better IMO. 
------------
=> Add write_atomnames option to xyz writer

mbuild/formats/charmm_writer.py, mbuild/formats/gomc_conf_writer.py, mbuild/tests/test_charmm_writer.py, mbuild/tests/test_gomc_conf_writer.py, mbuild/utils/reference/Charmm_writer_testing_only_zeolite.xml, mbuild/utils/specific_ff_to_residue.py
Addition of the non-orthogonal box and CIF reader capability for GOMC. Also, better formatting for the GOMC control file writer, a check to ensure the last free energy lambda value is 1, and a faked FF for zeolite testing for the test code.
Lastly, the removal of the box size changing from the specific_ff_to_residue.py and charmm_writer.py writers as this is more complicated and cumbersome with the non-orthogonal boxes, so it was removed.
This also changed:
- Formatting in the gomc_conf_file_writer to be cleaner. 
- PSF and PDB writer to write individual atoms for a fixed crystal structure with no bonds, which allows proper atom wrapping on GOMC. Previously, if it was listed as an atom if it was had the same residue name.
- Removed allowing box size changes in the Charmm object and the …
=> GOMC non-orthogonal box updates

mbuild/formats/cassandramcf.py
Previously, the MCF writer sorted the atom order for impropers based upon rules to match LEAP behavior discussed here (https://github.com/choderalab/openmoltools/issues/24). However, the problem with that is that the improper atom order in an  already-parameterized `parmed.Structure` is _modified at the file writing stage_. This means the MCF writer behaves differently than other writers, and can lead to inconsistency between different engines. There were also other problems with this choice, such as:
* Reading a .top -> parmed.Structure -> MCF and the atom order would end up with a different atom order (and energy!) than GROMACS.
* Sorting also implicitly assumed GAFF (which is not a terrible assumption for amber-style impropers)
------------
=> Remove improper atom sorting in MCF writer

mbuild/coordinate_transform.py, mbuild/tests/test_coordinate_transform.py
If you were to try and run the following, you'd get a `RemovedFuncError`
```
import mbuild as mb
from mbuild.coordinate_transform import x_axis_transform, y_axis_transform, z_axis_transform
comp = mb.load("CCCCCC", smiles=True)
z_axis_transform(comp)
```
```
RemovedFuncError: 
rotate_around_y() has been removed. Please use Compound.rotate_around_y().
Deprecated since mBuild version 0.7.0 and removed
in version 0.11.0.
```
The `y_axis_transform` and `z_axis_transform` functions within `coordinate_transform.py` were still calling deprecated functions. They now call the `Compound.rotate()` function and specify the correct axis to rotate around
I'll work on adding unit tests that probably should have caught this error earlier.
------------
=> Fix function calls in axis transform functions

Dockerfile, azure-pipelines.yml, mbuild/tests/test_lammpsdata.py, setup.cfg
Previously, all conda environment creations use `conda` for the
dependency resolution, which is notoriously slower than `mamba`'s
implementation.
This can have a noticeable impact on run times during CI as well as
building docker images. Mamba has replaced conda in our dockerfile as
well as our azurepipelines.yml file.
------------
=> Migrate azure pipeline environment creation to use mamba instead of conda

mbuild/compound.py, mbuild/tests/test_compound.py
Previously, when using openmm to energy minimize a `Compound`, there was
no way to use bond constraints during those steps.
This PR adds in the ability for the user to use openMM to constrain
either: 'AllBonds', 'HBonds', or 'HAngles' according to the
[parmed.structure.createSystem](https://parmed.github.io/ParmEd/html/api/parmed/parmed.structure.html#parmed.structure.Structure.createSystem)
------------
Closes #940
=> Allow compound.energy_minimize to use constraints

Dockerfile, devtools/docker-entrypoint.sh
While working with the latest mbuild docker image, I noticed that the
entrypoint script would fail due to an incorrect conda environement
name.
I also noticed in some cases where python would be updated to 3.9
instead of being fixed at 3.7. I think it is due to the second line
where we install jupyter with nomkl after we create the environment with
the environment.yml file. These have been updated and fixed now.
=> Update dockerimage information and entrypoint

docs/getting_started/installation/installation.rst
I am constrained to using a windows machine (for a few weeks). While I tried to install `mbuild` using the installation instructions, `conda` couldn't find appropriate executable for `packmol`. This PR adds instruction to install mbuild on Windows in our docs.
=> Add windows installation note

mbuild/formats/hoomd_forcefield.py, mbuild/formats/hoomd_simulation.py, mbuild/tests/test_hoomd.py, setup.cfg
The current default values for `r_cut` are 1.2 in both `hoomd_simulation.py` and `hoomd_forcefield.py`. Since these are in reduced units, this seems kind of small for an `r_cut` value. I believe the typical approach is to use `2.5` sigma or half the box length. It's easy enough for the user to change when calling these functions, but I feel like a more standard default value is needed.  
Please let me know what you think, or if I'm missing anything about why we'd prefer a default value of `1.2`
------------
=> Change default hoomd `r_cut` values to 2.5

environment-dev.yml, environment-win.yml, environment.yml, mbuild/compound.py
Currently our unit tests are failing for master due to `simtk`
references that are incompatible with openmm >= 7.6.
This updates the references and should fix the failing tests.
------------
=> Update openmm references in energy_minimize

mbuild/compound.py, mbuild/tests/test_compound.py
Found a bug in `mb.clone()` where the periodicity of the original compound is not included in the cloning process. This PR add a line to also clone periodicity. 
------------
=> Fix bug in mbuild clone

mbuild/formats/lammpsdata.py, mbuild/tests/test_lammpsdata.py
LAMMPS handles moleculeID's as an additional set of data to link atoms
with specific molecules (similar to residues in other engines).
However, there is a special case where the moleculeID is 0
>The molecule ID is a second identifier attached to an atom.
>Normally, it is a number from 1 to N, identifying which molecule the atom belongs to.
>It can be 0 if it is a non-bonded atom or if you don't care to keep track of molecule assignments.
In the lammpswriter case, the resid was always starting at 0, which was
treating the first molecule "residue" as a non-molecule.
Now, an additional flag `moleculeID_offset` will let the user change
this starting offset value if they want to use the previous starting
value of 0. The default behavior now is to start all IDs at 1.
------------
closes #950
=> Include moleculeID offset in lammpswriter

Dockerfile
Previously, the latest version of miniconda3 alpine docker image was incorrectly built as a debian image. This has now been fixed.
However, in between the previous version we have been using, the anaconda user was not added by default. I added the necessary adduser commands to fix this.
------------
Closes #944
=> Update docker image and re-add anaconda user

mbuild/packing.py, mbuild/tests/test_packing.py
Resolve #984. Modify `packing.solvate()` method to use clone of provided solute instead. 
------------
=> Use clone of solute in `packing.solvate()` method

mbuild/lattice.py
There was a small issue when trying to use the garnett in
`lattice.load_cif`, the garnett readers now use a standard
`garnett.reader` to access the various file readers. `load_cif` has been
updated to support this.
------------
=> Update the api for the cif file reader

mbuild/formats/hoomd_forcefield.py
OPLS 0th order term is not used by [HOOMD OPLS dihedral](https://hoomd-blue.readthedocs.io/en/latest/module-md-dihedral.html#hoomd.md.dihedral.OPLS) see [RB_to_OPLS note](https://github.com/mosdef-hub/mbuild/blob/8baa19a46d1ece809f214a2e1a2f8984dd923b56/mbuild/utils/conversion.py#L55). 
This PR fixes the OPLS conversion for HOOMD v3. The implementation is [already correct in HOOMD v2](https://github.com/mosdef-hub/mbuild/blob/8baa19a46d1ece809f214a2e1a2f8984dd923b56/mbuild/formats/hoomd_simulation.py#L446). Thanks to @bc118, @chrisiacovella, and @joaander for guidance!
------------
=> Fix incorrect indexing of force constants in HOOMD forcefield

docs/conf.py, docs/environment-docs.yml, environment-dev.yml, environment-win.yml, environment.yml, mbuild/compound.py, mbuild/tests/test_compound.py, mbuild/utils/io.py
After dealing with updates for our implementation of the periodicKDTree in mBuild, I have been increasingly in favor of using a different tool that might get us similar/same behavior without us having to also maintain this KDTree implementation that is over 10 years old, and has never been updated to take advantage of any KDtree updates in the scipy core.
`freud` seems like an excellent package that can handle not just rectangular bounding boxes (our current PKDTree can only handle rectangular boxes), but also triclinic!
This is an experimental feature and also depends on #968 .
Currently opening as a draft, since I need to test other features as well. 
------------
=> Generate bonds with freud

mbuild/formats/charmm_writer.py, mbuild/tests/test_charmm_writer.py, mbuild/utils/specific_ff_to_residue.py
- Removed the C0 or K0 dihedral term from the Charmm writer.  GOMC uses it as a dihedral constant, but the standard CHARMM format reads it as a harmonic potential (this includes NAMD). Therefore, this can cause errors that will be hard to see in any reader using the standard Chamm format (see attached file).
- Also, added a line to the specific_ff_to_residue.py file to prevent errors when multiple box sizes are used/merged.
------------
=> Removed the C0 or K0 dihedral term from the Charmm writer

azure-pipelines.yml
When upgrading from hoomd=3.0.0dev12 to hoomd=3.0.0dev13, calling the hoomd.md.special_pair.LJ constructor immediately errors out with a TypeError during initialization.
This pins hoomdv3 to dev12 until this issue is resolved.
------------
https://github.com/glotzerlab/hoomd-blue/issues/1202
=> Pin hoomdv3 to `dev12` until the issue with `hoomd.md.special_pair.LJ` in `dev13` is resolved

mbuild/formats/json_formats.py, mbuild/tests/test_json_formats.py
Fixes #1001, where sometimes `compound.pos` can be an array numpy dtypes (`np.float64`/ `np.float32`), converting them to a list using a list's constructor will not be able to cast them to python `float`. This PR fixes it.
=> Ensure positions are casted to python floats before conversion to json

mbuild/formats/json_formats.py, mbuild/tests/test_json_formats.py
Currently, box information is not written out/read in when saving/loading from json file format. This PR add that field during the writing/reading of json file. Relate to #1003 
------------
=> Include box info when writing/reading json file

mbuild/formats/cassandramcf.py, mbuild/formats/lammpsdata.py, mbuild/tests/test_lammpsdata.py
Unit tests were added to check for the indexing on each of these terms.
------------
=> Make Lammps Writer use correct indexing

mbuild/compound.py, mbuild/tests/test_compound.py
Raised by @daico007 in #1006, for very small molecules, the bounding
boxes will be so close to zero that the determinant of the box vectors
will be close to zero, signaling a co-linear box (psuedo-{1D, 2D}) and
raising an exception.
This PR provides an additional parmeter for the
`mb.Compound.get_bounding_box` method, `pad_box` which is a boolean to
avoid these co-linear systems by adding a 1nm pad to all box edges.
`pad_box` is `False` by default, and unit tests have been provided to
check both cases.
Closes #1006
------------
* #1006
=> Allow user to pad bounding box for small cmpds

environment-dev.yml, environment-win.yml, environment.yml, mbuild/compound.py, mbuild/tests/test_compound.py, setup.cfg
Previously, `mbuild.Compound.freud_generate_bonds()` method was silently
ignoring the provided periodicity of the compound and would not generate
non-periodic bonds at the boundary of the boxes.
This has been remedied, and since `freud` currently does not support
pair finding for non-periodic systems, a fix has been implemented to
support this by creating pseudo-periodic box dimensions for non-periodic
directions. No changes are needed by the user.
------------
=> Set periodicity correctly in freud_generate_bonds

MANIFEST.in
Missing file extensions are added to package MANIFEST.
=> Add missing file extensions in MANIFEST

CITATION.cff, setup.cfg
GitHub has added native support of the CITATION.cff file format, which
provides a nice way to generate a citation for a software repository.
This adds in a basic citation.cff file, which can be updated as
necessary.
------------
=> Add CITATION.cff file for easier repo citation

mbuild/compound.py
The current `Compound.is_independent()` is not very performant and @CalCraven found out that changing the check from `if neigh not in self` to if `neigh not in self.particles()` will significantly speed thing up. 
------------
=> improve performance of is_independent

mbuild/bond_graph.py, mbuild/compound.py, mbuild/conversion.py, mbuild/port.py, mbuild/tests/test_compound.py
Currently, compound bond graph only include bonded particles. This PR modify `mb.Compound` so that its bond graph also include independent/non-bonded particle. 
------------
=> Modify bond graph to include independent particle 

mbuild/bond_graph.py, mbuild/tests/test_coordinate_transform.py
=> Fix for bug with mbuild missing edges in bond graph

mbuild/compound.py, mbuild/formats/protobuf.py, mbuild/packing.py, mbuild/tests/test_compound.py
Changing the default value of `Compound.charge` and `Compound.mass` to `None`. The purpose is to distinct between whether the user intentionally setting the value of `charge` and `mass` or just haven't initiated those properties.  
------------
=> default mass and charge of Compound to  None

environment-dev-win.yml, environment-dev.yml, environment.yml, mbuild/conversion.py, mbuild/tests/test_gmso.py
With the new gmso release, the `refer_hierarchy` option can now be passed to gmso conversion methods. 
------------
=> add refer_inhierarchy to gmso conversion

.github/workflows/CI.yaml, .readthedocs.yml, environment-dev-win.yml, environment-dev.yml, environment.yml, mbuild/compound.py
Drop python 3.7 and add test for python 3.10, in coordination with similar move in foyer and gmso.
------------
=> drop py3.7 from testing

environment-dev-win.yml, environment-dev.yml, environment.yml, mbuild/compound.py, mbuild/conversion.py, mbuild/tests/test_compound.py
A quick path to go from mbuild compound to smiles string through openbabel. I am using openbabel to guess the bond orders of the resulted molecule and output a smile string. This can be a temp solution before we can have our own smiles string writer. Pending unit tests. 
------------
=> Add smiles string conversion using pybel backend

mbuild/compound.py, mbuild/coordinate_transform.py, mbuild/tests/test_coordinate_transform.py
Remove the removed methods from `coordinate_transform.py`. Add anchor option for `Compound.spin()`, so now the compound can choose an anchor to be any of its successors instead of just its center. 
Pending unit tests.
------------
=> Trim coordinate_transform.py, new features for spin method

mbuild/compound.py, mbuild/tests/test_compound.py
Fix bug related to get_boundingbox() when compound is in near-planar shape by defining tolerance when detecting missing dimension. Fix bug reported by Maxim in the dev channel.
------------
=> Fix bug related to `get_boundingbox()` 

mbuild/lib/recipes/alkane.py
Resolves #1068
------------
- [NA] Includes appropriate unit test(s)
- [NA] Appropriate docstring(s) are added/updated
=> Produce n=2 when ports are not capped

.github/workflows/CI.yaml, README.md, mbuild/compound.py, mbuild/tests/test_compound.py
Right now, if what of the check failed, all the other unfinished checks will get canceled, which miss the point of testing on different OS. This PR turns that off. 
------------
=> Turn off fail-fast

mbuild/compound.py, mbuild/formats/hoomd_snapshot.py, mbuild/tests/test_compound.py
energy minimization checks are now failing on ubuntu.  This PR is focused on trying to identify the issue.  
------------
=> Fixing energy minimization tests

.pre-commit-config.yaml, docs/topic_guides/coordinate_transforms.rst, mbuild/compound.py, mbuild/formats/hoomd_forcefield.py, mbuild/formats/hoomd_snapshot.py, mbuild/tests/test_compound.py, mbuild/tests/test_gmso.py
This is related to issue #1077.   Rather that relying on a temporary .mol2 file to perform open babel energy minimization, this PR will directly set the relevant parameters in the open babel OBMol class, and extract energy minimized coordinates from this class for updating of the positions in the Compound. 
My initial plan was to simply store Compound.name information, overwrite it with Compound.element before generating the .mol2 file, and then revert Compound.name parameters to the original entries.  However, using the API directly to set the info seems like it would be better with less overhead.  
------------
=> updating open babel energy minimization to no longer use temp file

.pre-commit-config.yaml, docs/sphinxext/notebook_sphinxext.py, mbuild/compound.py, mbuild/formats/cassandramcf.py, mbuild/formats/lammpsdata.py, mbuild/lattice.py, mbuild/lib/recipes/monolayer.py, mbuild/lib/recipes/tiled_compound.py, mbuild/packing.py, mbuild/pattern.py, mbuild/tests/test_compound.py, mbuild/tests/test_packing.py, setup.py
Addresses #1080. Added some more aggressive input checks around the `bounds` arg for `fill_region`. Not sure if new unit tests are warranted but happy to add if so.
------------
=> Issue 1080

mbuild/formats/cassandramcf.py, mbuild/tests/test_cassandramcf.py
This PR increases the number of decimal places for LJ parameters from 3 to 5 in the Cassandra MCF writer.  See #1093  .
Closes #1093 .
------------
=> Write LJ parameters with 5 decimal places instead of 3 with MCF writer.

environment.yml
=> Add networkx to environment.yml

mbuild/compound.py, mbuild/conversion.py, mbuild/tests/test_compound.py
This refers to issue #1104 . This PR aims to improve the performance of the Compound.add function and loading routines that rely upon it. 
The basic gist, as outlined in the issue above, is that when constructing a compound using the add function, the performance can degrade as the compound grows in size, due to the repeated merging  (i.e., composing) of bond_graphs,  specifically, merging a small with a large bond graph over and over again.  This PR changes the underlying logic such that if a list of Compounds is passed to the add function, it will use the compose_all function to merge these bond_graphs together, before adding to the root Compound (and merging bond_graphs with the root compound).   The compose_all function effectively scales with the number of compounds being merged. …
=> speeding up add function for large compounds

.github/workflows/CI.yaml, environment-dev-win.yml, environment-dev.yml, environment.yml, mbuild/lib/recipes/alkane.py
I think it's time we need to add support/test for python 3.10 and 3.11. 
------------
=> Add testing for py3.10 and 3.11

mbuild/formats/lammpsdata.py
This PR looks to add more sorting to the lammpswriter, such that the ordering is done similar to the angles and bonds, which are prioritized not by their position in the parmed structure, but by the indexes of their component atom_types.
------------
=> Extend ordering of rb torsions written out from parmed structure

mbuild/coarse_graining.py, mbuild/compound.py
After the discussion with @chrisiacovella, we have decided it would be faster to store `Compound.children` with `list` instead of the in house `OrderedSet`. The replacement will speed up both the `Compound.add` step by removing the comparing stage when adding new children to a set, and the indexing (getting element from a list/set by index). We realized the latter was the cause for https://github.com/mosdef-hub/mbuild/issues/1114, not directly the `Compound.add_bond` itself, but how the `particle` is retrieved from `Compound.children` to perform the addition. 
------------
=> Use list to store compound.children

mbuild/formats/lammpsdata.py
Fix the docstring for LAMMPS improper writers. 
------------
=> Fix lammps impropers docstring

mbuild/compound.py, mbuild/tests/test_compound.py
This addresses issue #1125 whereby the freud_generate_bonds routine was not finding all bonds when looking for bonds between two different species 
As detailed in the issue, this was caused by the way in which we pass the  particles to freud during the calculation of neighbors. Ultimately, the fix for this is relatively straight forward to implement.  If name_a == name_b, then  exclude_ii = True; If name_a != name_b, then exclude_ii = False.  This is now automatically toggled by the code, and users no longer have the option to change this. 
An additional test is included now that looks at a system where the two specifies are unique, as the original tests did not include this. 
------------
=> fixed freud bond issue

environment-dev-win.yml, environment-dev.yml, environment.yml, mbuild/formats/gsdwriter.py, mbuild/formats/hoomd_snapshot.py, mbuild/tests/test_compound.py, mbuild/tests/test_gsd.py, mbuild/tests/test_hoomd.py
Similar to https://github.com/mosdef-hub/gmso/pull/739 this PR updates the `gsd.hoomd` class names used from `Snapshot` to `Frame`. The write modes are also updated. 
Addresses #1130 if we decide to pin gsd to >= 2.9 which we talked about [Here](https://github.com/mosdef-hub/gmso/issues/738)
------------
- [x ] Includes appropriate unit test(s)
- [ x] Appropriate docstring(s) are added/updated
- [ x] Code is (approximately) PEP8 compliant
- [ x] Issue(s) raised/addressed?
=> Support GSD >= 2.9

.github/workflows/CI.yaml, environment-dev-win.yml, environment-dev.yml, environment.yml, mbuild/conversion.py
Since the method used to pull residues in our parmed conversion is not yet optimized, I think it makes more sense to have that off right now, since it may cause significant slow down for larger system. May fix this #1133.
------------
=> Turn off the infer_residues when converting to pmd

mbuild/compound.py, mbuild/tests/test_compound.py
This is a follow up PR to #1134. Turn out, my initial instinct was correct, in that the slow down was cause by the `infer_residues` in parmed conversion. The reason the last PR doesn't show any improvement is because I forgot to also the `infer_residues` in the `to_parmed` existing in `compound.py` (I only turned off in `conversion.py`). 
------------
=> Turn off the infer_residues in compound.py

mbuild/formats/xyz.py, mbuild/packing.py
This address issue #1139 .  Loading of xyz files did not see the prior changes to adding multiple compounds as a single list, rather than one at a time. 
------------
=> revised load_xyz function

mbuild/tests/test_compound.py
Fix test that checked for the output of `show_hierarchy`.  Relate to #1141 
------------
=> Fix Treelib test

mbuild/compound.py, mbuild/conversion.py
Add more doc strings to be explicit about saving out compounds into various formats.
------------
=> Added extensions to savers doc string

mbuild/packing.py, mbuild/tests/test_packing.py
Add option to (not) center the solute in `mb.packing.solvate`, will address https://github.com/mosdef-hub/mbuild/issues/974. Pending unit test.
------------
=> Add new option for packing.solvate

mbuild/compound.py
Add `verbose` option for `add` method in `Compound.add()`. When provided a list of compound to `Compound`, the method would recursively calling itself to add each compound. During this process, there is a final step to check if the new compound bounding box is bigger than the `Compound.Box`. The time for `Compound.get_boundingbox()`, however, would really add up in this process (scale up really badly if you get to the >10,000 range). Hence, I am adding an `verbose` option for this method to be able to turn it off when adding individual particle if a list/iterable is provided. 
------------
=> Add `check_box_size` option for `add` method in `Compound.add()`

mbuild/conversion.py
Address #1152. Add new default option for `Compound.save()` (`None`), which will use combining rule from XML. 
------------
=> Add new default option for Compound.save()

mbuild/compound.py
fixed the issue not being able to print the hireachy. 
related to the issue (https://github.com/mosdef-hub/mbuild/issues/1143)
------------
=> fixed the tree print issue

.github/workflows/CI.yaml, Dockerfile
Update several syntaxes in CI.yml (to use latest actions for docker). Fix deprecated fields for python version. 
------------
=> Update deprecated syntax in CI.yml

mbuild/compound.py
Fixes #1157 
Allow a user to adjust the bead size in Jupyter notebook visualization. This is especially useful for CG models where the default bead size may be too small.
------------
=> Added ability to adjust bead_size

mbuild/compound.py, mbuild/conversion.py, mbuild/formats/json_formats.py, mbuild/tests/test_json_formats.py
Address #1162. Add some workaround to the ind particle bond graph before adding to the main compound and speed up the loader in general. 
```python
import mbuild as mb#
eth = mb.load("CC", smiles=True)
eth.name = "Ethane"
eth_box = mb.packing.fill_box(
compound=eth,
n_compounds=1000,
box=[5, 5, 5]
)
eth_box.name = "EthaneBox"
eth_box.save("eth_box1000.json", overwrite=True)
comp = mb.load("eth_box1000.json") # This now takes a few second. 
```
------------
=> Speed up json loader

docs/conf.py, docs/docs-env.yml, docs/getting_started/installation/installation.rst, docs/getting_started/writers/writers.rst
Turn out, even though the docs build on readthedocs pass, some of the pages still failed to be built (but didn't error out). This PR will try to fix the remaining issue with the docs and addressed the issue raised in #1174. 
------------
=> Fix failing doc build

mbuild/tests/test_compound.py, mbuild/tests/test_packing.py
Update packmol arguments to raise Errors on overlapping molecules on overpacked boxes, and reduce overlaps argument for test cases.
------------
=> Fix failing tests with latest version of packmol

mbuild/lib/recipes/polymer.py, mbuild/tests/test_compound.py, mbuild/tests/test_polymer.py
This is a small PR that changes how the capping hydrogen compounds are added to the polymer that is built up in the polymer builder. Right now, we add the hydrogen compounds to the polymer compound, so they are at the same hierarchical level as the monomer compounds. This PR now adds them to the head and tail monomers. This is cleaner, and creates a more consistent hierarchy that we would expect with a polymer compound, where its children are the monomers, instead of particles.  You can see in these 2 examples below:
```
import mbuild as mb
from mbuild.lib.recipes import Polymer
chain = Polymer()
chain.add_monomer(compound=mb.load("CC", smiles=True), indices=[4,7], separation=0.145)
chain.build(n=6, sequence="A")
```
Current behavior:
```
>>> chain.children
[<Compound 6 particles, 5 …
```
=> Add cap hydrogens to head and tail compounds in the polymer builder

mbuild/compound.py, mbuild/conversion.py, mbuild/coordinate_transform.py, mbuild/lattice.py, mbuild/packing.py, mbuild/port.py, mbuild/utils/decorators.py, mbuild/utils/io.py, mbuild/utils/jsutils.py
This is a PR that does 2 things:
1) Fix a deprecation warning that is being raised about `find_executable` in `distutils`
```
>>> from distutils.spawn import find_executable
>>> find_executable("PACKMOL")
<stdin>:1: DeprecationWarning: Use shutil.which instead of find_executable
```
2) It also replaces `.format()` with f-strings in many places in an effort to clean things up a bit (I was bored at an airport)
------------
=> Fix deprecation warnig in `packing.py` and replace `.format()` with f-strings where possible.

mbuild/compound.py, mbuild/coordinate_transform.py, mbuild/tests/test_compound.py
This PR resolves #1194 
This PR added the reset_labels kwarg to force_overlap with a default of False. In order to reset the labels as will, that code has been moved to a new method, Compound.reset_labels.
------------
=> reset_labels kwarg to force_overlap, new method reset_labels

mbuild/conversion.py, mbuild/tests/test_compound.py
Updating the loading paths to deal with issues loading long strings as smiles. Initial loading uses the Path package to check if the path exists, before checking to see if rdkit can load a valid smiles file. However, Path throws an error if the Path is too long:
```
"name": "OSError",
"message": "[Errno 63] File name too long: 'CC1C(=O)NC(C(=O)NC(CSC(C2=C(C3=CC4=C(C(SCC(C(=O)N1)NC(=O)C(CCCCN)NC(=O)C(CCC(=O)N)NC(=O)C(C(C)C)N)C)C(=C([N-]4)C=C5C(=C(C(=N5)C=C6C(=C(C(=CC2=N3)[N-]6)C)CCC(=O)[O-])CCC(=O)[O-])C)C)C)C)C(=O)NC(CC7=CNC=N7)C(=O)NC(C(C)O)C(=O)NC(C(C)C)C(=O)NC(CCC(=O)[O-])C(=O)[O-])CCC(=O)N.[Na+].[Na+].[Na+].[Na+].[Fe+2]'",
```
This PR better handles this type of smiles, and also splits the handling of the rdkit and pybel backends for smiles loading, both from files and from strings. …
=> Reformat loaders for different smiles paths

.github/workflows/CI.yaml, Dockerfile, environment-dev.yml
The docker build is failing after the change from `setup.py` to `pyproject.toml`. While fixing that, I figured we could switch to a mamba and ubuntu-based image [(here)](https://hub.docker.com/r/condaforge/miniforge3) instead of an anaconda and alpine one [(here)](https://hub.docker.com/r/continuumio/miniconda3) since the current workflow installs mamba anyway.
=> Fix and update Dockerfile

docs/docs-env.yml, environment-dev.yml, environment.yml, mbuild/utils/io.py
This is in the standard library as of Python 3.10, so the third-party backport is not needed
------------
=> Drop `importlib.resources` backport

environment-dev.yml
I think the dev environment should include py3Dmol. We could have a separate discussion if it should be included in the conda-forge package dependencies as well.
------------
=> Add py3Dmol to dev env file

.github/workflows/CI.yaml, README.md, environment-dev.yml, environment.yml, mbuild/tests/test_lattice.py, mbuild/tests/test_packing.py, mbuild/utils/io.py, pyproject.toml
This pins the numpy version used in the environment.yml files to >=2.0 and <2.3.
There are breaking changes in some upstream packages in 2.3 (https://github.com/ParmEd/ParmEd/issues/1406)
There were a couple syntax changes needed in some unit tests. Tests with numpy 2 are passing in gmso as well, so I'll start a PR there. I'll check in foyer and ffutils next.
------------
=> Use numpy 2 in CI testing. Drop python 3.9, add python 3.13 to testing, remove openbabel from `enviroment-dev.yml`

mbuild/tests/test_packing.py
Packmol had a bug fix recently and a new release on conda-forge about a week ago. I think this was changing the behavior of the initial guess (using sidemax). The `test_sidemax` tests are failing as a result. From what I can tell, the issue stems from using too large of a box size combined with large sidemax values (2000 nanometers), which is causing the packing calls in the test to use a ton of memory. It was up to 28GB when running the same test in a notebook
------------
=> Fix sidemax test in `test_packing.py` by using a more reasonable length
