- mbuild/coordinate_transform.py
- mbuild/tests/test_coordinate_transform.py
Also updated errors I saw in coordinate_transform
> Added unit tests for coordinate_transform

- mbuild/atom.py
- mbuild/coordinate_transform.py
- mbuild/examples/methane/methane.py
- mbuild/tests/base_test.py
- mbuild/tests/test_coordinate_transform.py
Now has a z-axis transform method and is the equivalence transform and apply_to are updated for using atoms.
> Updated coordinate_transform.py

- mbuild/compound.py
- mbuild/examples/tnp/tnp.py
- mbuild/tests/test_compound.py
Still need unit tests.
Resolves #97
> [WIP] Implement `add_bonds` and `atoms_in_range`.

- mbuild/compound.py
> Better __repr__ for Compound.

- devtools/conda-recipe/meta.yaml
- mbuild/compound.py
> Replace custom OrderedSet with conda installable.

- mbuild/compound.py
- mbuild/examples/alkane/alkane.py
- mbuild/examples/tnp/tnp.py
- mbuild/recipes/polymer.py
- mbuild/recipes/tiled_compound.py
- mbuild/tests/test_compound.py
- mbuild/tests/test_coordinate_transform.py
Bonds have been restructured. Now the bond graph is always contained in the top level component only.
> restructured bonds

- devtools/travis-ci/post_binstar.sh
- mbuild/examples/coarse_graining/hexane_box.py
- mbuild/examples/tnp/tnp.py
- mbuild/examples/tnp/tnp_box.py
Token variable name has changed.
> Fix conda deploy

- .travis.yml
- mbuild/tests/test_compound.py
Tests for problems encountered in #142
> Added unit test

- mbuild/compound.py
- mbuild/packing.py
Also fix small bug in packing by casting number of input molecules to
int before plugging into template
> Call particles() on a particle returns self

- mbuild/compound.py
- mbuild/tests/test_compound.py
Also added an appropriate test
> Check for bond graph before trying to remove particle

- mbuild/compound.py
- mbuild/coordinate_transform.py
- mbuild/examples/alkane_monolayer/alkane_monolayer.py
- mbuild/examples/pmpc/pmpc_brush_layer.py
- mbuild/pattern.py
- mbuild/port.py
- mbuild/recipes/monolayer.py
- mbuild/tests/test_monolayer.py
Added 'used' attribute to Port to monitor availability; updated examples; added test for mixed monolayer
> Monolayer recipe now supports arbitrary number of chain types

- mbuild/compound.py
- mbuild/formats/README.txt
- mbuild/formats/hoomdxml.py
- mbuild/formats/lammpsdata.py
- mbuild/periodic_kdtree.py
- mbuild/recipes/tiled_compound.py
- mbuild/tests/test_compound.py
- mbuild/tests/test_hoomdxml.py
- mbuild/tests/test_lammpsdata.py
- mbuild/tests/test_silica_interface.py
- mbuild/tests/test_tiled_compound.py
The primary issue was that the cKDTree behavior changed. I still haven't pinned down exactly how it changed but this fixes our immediate problem.
The TiledCompound fix from #195 is also in as well as some minor PEP8 updates.
Resolves #203
> Fix KDTree and TiledCompound bugs

- mbuild/bond_graph.py
Essentially copied the code from the analogous networkx function, with a few minor changes to work with the mbuild.BondGraph object.
> connected_components now mirrors networkx behavior

- mbuild/compound.py
- mbuild/coordinate_transform.py
- mbuild/examples/alkane/alkane.ipynb
- mbuild/examples/alkane/alkane.py
- mbuild/examples/test_examples.py
- mbuild/exceptions.py
- mbuild/recipes/tiled_compound.py
- mbuild/tests/test_compound.py
- mbuild/tests/test_tiled_compound.py
- mbuild/utils/io.py
Apparently I've mucked up my git log...
> Add more specific exceptions and unit tests

- mbuild/bond_graph.py
Also renames the `data` attribute to the slightly more descriptive `adj` for "adjacency".
> Minor bondgraph optimizations

- mbuild/packing.py
- mbuild/tests/test_packing.py
> Allow packing of boxes not anchored at origin

- mbuild/recipes/silica_interface.py
- mbuild/tests/test_silica_interface.py
A seed argument has been added to the silica interface recipe so that interfaces may be easily recreated.
> Added seed to silica interface recipe and added unit test

- docs/tutorials/tutorial_polymers.ipynb
- docs/tutorials/tutorial_polymers.rst
- docs/tutorials/tutorials.rst
I added a tutorial about constructing polymer systems.
> added a tutorial on constructing polymers

- mbuild/pattern.py
- mbuild/tests/test_pattern.py
With this commit, you can scale the points in a Pattern with the
constructor, e.g.,
```python
grid = mb.Grid2DPattern(2, 2, scale=3)
```
> Scale pattern in Pattern.__init__()

- mbuild/pattern.py
> Docstring editing

- mbuild/coarse_graining.py
- mbuild/tests/base_test.py
- mbuild/tests/test_pattern.py
Coarse graining code definitely needs more testing coverage and people using it to discover pain points.
Resolves #314
> Fix bug in coarse graining bond creation

- mbuild/tests/test_coarse_graining.py
> Add unit test for CG

- mbuild/formats/hoomdxml.py
> Add wrap_coordinates arg to hoomd writer

- mbuild/compound.py
- mbuild/tests/test_compound.py
> Implement residue name specification when saving

- mbuild/compound.py
Addresses some of the concerns in https://github.com/mosdef-hub/mbuild/issues/349
> Avoid building list of parmed coordinates

- mbuild/compound.py
- mbuild/tests/test_compound.py
- mbuild/utils/io.py
Resolves https://github.com/mosdef-hub/mbuild/pull/352
> Use Parmed loaders by default, remove Mdtraj dependency

- mbuild/lib/atoms/c3.py
- mbuild/lib/atoms/h.py
- mbuild/lib/atoms/n4.py
- mbuild/lib/bulk_materials/amorphous_silica.py
- mbuild/lib/moieties/ch2.py
- mbuild/lib/moieties/ch3.py
- mbuild/lib/moieties/ester.py
- mbuild/lib/moieties/h2o.py
- mbuild/lib/moieties/peg.py
- mbuild/lib/moieties/silane.py
- mbuild/lib/surfaces/amorphous_silica.py
- mbuild/lib/surfaces/betacristobalite.py
- mbuild/recipes/polymer.py
> Removed 'compound.visualize()' commands outside interactive notebooks

- mbuild/coordinate_transform.py
- mbuild/tests/test_coordinate_transform.py
functions to observe np.ndarrays and lists
> These changes now allow the x/y/z_axis_transform

- mbuild/packing.py
> Change tolerance precision passed to packmol

- changelog.md
- mbuild/formats/hoomdxml.py
- mbuild/utils/decorators.py
This fixes half of issue #447, I still need to add the `auto_scale=True` but I wanted that as a separate PR since that seems like a larger change. If you want I can make them the same PR.
> added unit conversions to get to kJ/mol, nm, amu

- mbuild/compound.py
- mbuild/tests/test_compound.py
- mbuild/utils/io.py
Part of #483 (and I guess older stuff? #58)
> Add to_networkx function

- .travis.yml
- README.md
- requirements-dev.txt
Just messing around with codecov
> Add codecov basics

- mbuild/compound.py
> Fix updating coordinates from mdtraj Trajectory

- devtools/conda-recipe/meta.yaml
- mbuild/tests/test_compound.py
- requirements-dev.txt
A minor oversight merging #422 in
> Fix some dependencies

- mbuild/examples/alkane_monolayer/alkane_monolayer.py
- mbuild/examples/pmpc/pmpc_brush_layer.py
Update examples, which were not using the proper path, for the new recipes layout
------------
> Update examples for new recipes layout

- mbuild/examples/alkane_monolayer/alkane_monolayer.ipynb
- mbuild/examples/pmpc/pmpc_brush_layer.ipynb
Update the new path for Monolayer (mbuild.lib.recipes.Monolayer)
Update the jupyter notebook examples with the new recipes layout. 
------------
> Update jupyter notebook in examples

- mbuild/compound.py
- mbuild/tests/test_compound.py
Addresses #451. I can add this to `to_trajectory` if desired.
Travis was catastrophically failing on my branch
> Infer resnames

- .coveragerc
- mbuild/box.py
- mbuild/compound.py
- mbuild/examples/alkane/alkane.py
- mbuild/examples/alkane_monolayer/alkane_monolayer.py
- mbuild/examples/bilayer/bilayer.py
- mbuild/examples/lennard_jones/monolj.py
- mbuild/examples/pmpc/brush.py
- mbuild/examples/pmpc/pmpc_brush_layer.py
- mbuild/formats/gsdwriter.py
- mbuild/lattice.py
- mbuild/lib/recipes/monolayer.py
- mbuild/lib/recipes/silica_interface.py
- mbuild/lib/surfaces/betacristobalite.py
- mbuild/packing.py
- mbuild/tests/test_box.py
- mbuild/tests/test_compound.py
- mbuild/tests/test_utils.py
https://lgtm.com/projects/g/mosdef-hub/mbuild/
I went through little style nits that LGTM suggested and implemented them. Next I'm going to see if coveralls/codecov find major holes in the tests.
------------
> Implement some style suggestions by linters

- mbuild/compound.py
> Clone compound, modify cloned particles, save and viz clone

- mbuild/compound.py
This is a small change to compound.py file, where I have added few lines of extra documentation
> Minor Change to compound.py docs

- mbuild/packing.py
Some of the helper functions and inputs were not documented
in `packing.py`.
This PR addresses this and provides additional documentation for the
packing methods and helpers.
------------
- [n/a] Includes appropriate unit test(s)
- [n/a] Issue(s) raised/addressed?
> Update documentation of `packing.py`

- mbuild/compound.py
- mbuild/coordinate_transform.py
Small additions to `compound.py` and `coordinate_transform.py` functions.
------------
> Updates to mBuild documentation

- mbuild/compound.py
- mbuild/tests/test_compound.py
Added a `get_smiles` method to the `Compound` class. 
------------
> added get_smiles method and test

- mbuild/lib/recipes/silica_interface.py
- mbuild/tests/test_silica_interface.py
Update naming convention to cope with recent mbuild update. Refer to #587. 
------------
> OS naming bug fix

- mbuild/compound.py
- mbuild/formats/json_formats.py
- mbuild/tests/test_compound.py
- mbuild/tests/test_json_formats.py
This PR is for addressing #581, specifically converting compounds to JSON, adding option to convert `Port` information. 
------------
> Converting Compounds to JSON

- devtools/conda-recipe/meta.yaml
Updates the conda recipe to include the pytest arguments added in #590 for better parity between travis and conda/appveyor
------------
> Add nbval to conda recipe

- mbuild/coarse_graining.py
- mbuild/compound.py
- mbuild/formats/vasp.py
Just seeing if the app is installed correctly and what it does
------------
> Tiny style fixes suggested by LGTM

- azure-pipelines.yml
#615 Continues, with a change in testing strategy for windows, with added compulsory `cron` jobs.
------------
> Modifications to AZP test on windows

- devtools/travis-ci/install.sh
similar to https://github.com/mosdef-hub/foyer/pull/300. This PR tries to download `Miniconda` using `curl`.
> Fix Travis Build Errors

- devtools/conda-recipe/meta.yaml
Add `nbval` as a requirements for conda testing
------------
> Updates to conda build test requirements

- README.md
https://github.com/mosdef-hub/mbuild/issues/639, may wish to merge #634 first
View the rendered markdown here: https://github.com/mattwthompson/mbuild/blob/README-recipes/README.md
> Add recipe links to README

- mbuild/utils/io.py
Add `protobuf` installation message to `io.py` per #596. 
------------
> add protobuf to io.py

- docs/installation.rst
This:
is backwards - the first channel listed in this one-liner is the higher priority channel. Note that the instructions later, and the instructions in the foyer docs, appear to be fine `¯\_(ツ)_/¯¯\_(ヅ)_/¯¯\_(ツ)_/¯¯\_㋡_/¯🤷🤷‍♂(ツ)(ヅ)(ツ゚)㋡ت☝(ツ)✌(ツ)ᕦ(ツ)ᕤ(ツ)[̲̅$̲̅(ツ)$̲̅]( ͡° ͜ʖ ͡°)ಠ_ಠ¯\(°_o)/¯¯\_( ͡° ͜ʖ ͡°)_/¯ `
------------
> Update conda channel order in on-liner in installation docs

- devtools/travis-ci/install.sh
> Fix conda download URL in travis install (Closes #723)

- docs/installation.rst
> Fix links in docs/installation.rst

- Dockerfile
- devtools/docker-entrypoint.sh
- docs/docker.rst
- entrypoint.sh
The goal of this PR is to simplify the commands required to run docker. The current docker usage is described in our docs [here](https://mbuild.mosdef.org/en/stable/docker.html). Launching docker with `jupyter` requires the following command: 
```
docker run -it --name mbuild -p 8888:8888 mosdef/mbuild:latest su anaconda -s /bin/sh -l -c "jupyter-notebook --no-browser --ip="0.0.0.0" --notebook-dir /home/anaconda/mbuild-notebooks"
```
IMO, part of the goal of the docker builds is to "simplify" the process of getting "off the ground" with `mbuild`. That command leaves room for improvement.
```
docker run -it --name mbuild -p 8888:8888 mosdef/mbuild:latest
```
```
docker run --mount type=bind,source=$(pwd),target="/home/anaconda/data" mosdef/mbuild:latest "python data/test.py" 
```
``` …
```
> Simplify docker behavior

- mbuild/conversion.py
> Set ignore_box_warn to True for loading SMILES

- Dockerfile
- azure-pipelines.yml
- docs/installation.rst
> Remove channel mosdef and Test python 3.8 in azp

- mbuild/lib/molecules/__init__.py
- mbuild/lib/molecules/water.py
- mbuild/tests/test_lib_molecule.py
Closes #841. 
Some of the water models are very similar. I am happy to take suggestions for how to cut back on some of the code. 
------------
> Add library molecules for water models

- README.md
- mbuild/compound.py
- mbuild/tests/test_compound.py
Fix bug mentioned here #829.
------------
> Convert input to np.array in compound xyz setter

- .pre-commit-config.yaml
Previously, when we introduced pre-commit, it required users to manually
run the pre-commit hook locally.
Now, these pre-commit features can be run in the cloud now, which can be
useful for users that might not want to install the required packages.
This introduces the yaml configuration necessary to autoformat PRs
according to our current configuration.
------------
> Allow pre-commit to autoformat prs

- environment-dev.yml
- environment-win.yml
Pin foyer version to 0.9.2 to address the combining rule issue. 
------------
> pin foyer version to 0.9.2 in yml

- mbuild/conversion.py
Minor update to the docstring in the `load` function in `conversion.py`. Raised by @rmatsum836  [here](https://github.com/mosdef-hub/mbuild/issues/867#issuecomment-831450274)
------------
> Update for docstring in conversion.py

- mbuild/formats/lammpsdata.py
This is the pull request for solving issue 962
------------
> commit for issue 962

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
Minor fix to mbuild version command
------------
> Fix mbuild version command in ISSUE TEMPLATE

- mbuild/formats/hoomd_forcefield.py
> Add buffer argument for neighborlist

- azure-pipelines.yml
After #971, I think it would be better to test against both latest commit of foyer and gmso. This PR modify the current azure bleeding test to do so.    
------------
> Modify bleeding test

- .pre-commit-config.yaml
Exclude the setup.cfg file which is modified by `bump2version` each release.
------------
> Exclude setup.cfg

- CITATION.cff
- mbuild/tests/test_monolayer.py
Fix validation errors for the cff file.
------------
> Fix validation errors for cff file.

- mbuild/formats/lammpsdata.py
> Lammps lj unit charges

- mbuild/formats/hoomd_forcefield.py
- mbuild/formats/hoomd_snapshot.py
Address #1126, update check and handle hoomd 4 dihedral.
> handle hoomd 4

- .github/workflows/CI.yaml
- Dockerfile
- docs/docs-env.yml
Another attempt to fix Dockerfile, based on https://github.com/GOMC-WSU/MoSDeF-GOMC/pull/74. 
------------
> Fix Docker build 

- mbuild/compound.py
> Remove experimental feature tag for freud generate_bonds
